apiVersion: workspaces.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: test-ssm-workspace
  namespace: default
spec:
  displayName: "Test SSM Workspace"
  image: "public.ecr.aws/sagemaker/sagemaker-distribution:3.2.0-cpu"
  containerConfig:
    command: ["jupyter", "lab", "--core-mode", "--ip", "0.0.0.0", "--port", "8888"]
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  desiredStatus: "Running"
  accessStrategy:
    name: aws-ssm-remote-access
