# Example WorkspaceTemplate with custom idle detection endpoint
apiVersion: workspaces.jupyter.org/v1alpha1
kind: WorkspaceTemplate
metadata:
  name: custom-endpoint-template
spec:
  displayName: "Custom Endpoint Template"
  description: "Template with custom idle detection endpoint for different Jupyter flavors"
  defaultImage: "quay.io/jupyter/scipy-notebook:latest"
  defaultResources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  # Custom idle detection endpoint
  defaultIdleShutdown:
    enabled: true
    timeoutMinutes: 4  # 4 minutes for testing
    detection:
      httpGet:
        path: "/api/sessions"  # Different endpoint
        port: 8080             # Different port
  # Allow overrides but with tight bounds
  idleShutdownOverrides:
    allow: true
    minTimeoutMinutes: 2   # At least 2 minutes
    maxTimeoutMinutes: 8   # At most 8 minutes