# Example Workspace using Jupyter template with idle shutdown override
apiVersion: workspaces.jupyter.org/v1alpha1
kind: Workspace
metadata:
  name: workspace-jupyter-override
  namespace: default
spec:
  displayName: "Jupyter Workspace with Idle Override"
  templateRef: "jupyter-lab-template"
  desiredStatus: "Running"
  # Override idle shutdown timeout (within template bounds)
  idleShutdown:
    enabled: true
    timeoutMinutes: 5  # 5 minutes (within 1-10 range)
    # Keep template's Jupyter Lab command and detection config